# .github/workflows/hugo.yml
name: Build Hugo Site
on:
    push:
        branches: [main]
        # Ta bort paths så det triggar på alla ändringar

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              # Ta bort submodules: true

            - name: Setup Hugo
              uses: peaceiris/actions-hugo@v2
              with:
                  hugo-version: 'latest'

            - name: Build
              run: cd website && hugo --minify

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./website/public
                  #cname: en.zombie.nu
                  enable_jekyll: false
